source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'json'
gem 'jquery-rails'

# Rails 3.1 - Asset Pipeline
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# user management and puavo integration
gem 'ruby-ldap', :require => 'ldap'
gem "authlogic", '>= 3'
gem 'declarative_authorization'
gem 'puavo-client'

# httparty "makes consuming restful web services dead easy."
gem 'httparty'

# iivari features
gem "simple_form"
gem "responders"
gem 'tiny_mce'
gem 'acts_as_list'
gem 'rmagick', :require => 'RMagick'

group :development do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem "ruby-debug"
  gem 'mongrel'
  gem 'rspec-rails', '>= 2.8.1'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'sinatra'
end

group :production do
  gem "pg"
end
